services:
  - type: web
    name: studenthub
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 2H
      - key: ACCESS_REFRESH_TOKEN
        sync: false
      - key: REFRESH_TOKEN_EXPIRY
        value: 1d
